from sqlalchemy import Table, Engine, MetaData
from sqlalchemy.ext.asyncio import AsyncEngine
from typing import overload, Any

class CustomTable(Table):
    def __getattr__(self, attr: str) -> Any: ...
    def __bool__(self) -> bool: ...
    def as_pydantic(self, *, partial: bool = False) -> type: ...
    def as_pydantic_partial(self) -> type: ...
    def as_sqlmodel(self) -> type: ...

class LazyDB:
    engine: Engine
    schema: str | None
    cache_ttl: float | None

    def __getattr__(self, name: str) -> CustomTable: ...
    def invalidate(self, table_name: str) -> None: ...
    def invalidate_all(self) -> None: ...
    def preload(self, *table_names: str) -> None: ...
    def list_tables(self) -> list[str]: ...

class AsyncLazyDBAccessor:
    engine: AsyncEngine

    async def get(self, table_name: str) -> CustomTable: ...
    async def invalidate(self, table_name: str) -> None: ...
    async def invalidate_all(self) -> None: ...

@overload
def get_lazy_class(engine: Engine, *, cache_ttl: float | None = None, schema: str | None = None) -> LazyDB: ...
@overload
def get_lazy_class(engine: AsyncEngine, *, cache_ttl: float | None = None, schema: str | None = None) -> AsyncLazyDBAccessor: ...

class LazyAlchemyError(Exception): ...
class TableNotFoundError(LazyAlchemyError): ...
class ReflectionError(LazyAlchemyError): ...